my_nouns = {
	'umbrage':'displeasure; the vaguest feeling of suspicion',
	'requisition':'demand',
	'exegesis':'critical explanation/interpretation of a text, especially the Bible',
	'jaundice':'being in the state of resentment, prejudice, envy; skin discoloration',
	'maxim':'general truth or principle',
	'cupidity':'eager or excessive DESIRE',
	'approbation':'approval',
	'diatribe':'sharp bitter criticism',
	'wile':'trick; deceitful cunning',
	'predilection':'partiality',
	'affectation':'conspicuous artificiality; pretend quality',
	'callousness':'hardness; lack of sensitivity',
	'anodyne':'painkiller (medicine)',
	'dross':'waste',
	'compendium':'summary or full list of inventory',
	'defalcation':'misappropriation of money by fiduciary',
	'acumen':'keen insight, shrewdness',
	'polemic':'a controversial argument; a contrarian/contraversialist',
	'chicanery':'trickery by sophistry',
	'sedition':'rebellion',
	'perspicacity':'keenness; understanding; penetration',
	'minutia':'precise details; small/trifling matters',
	'panoply':'a wide-ranging array; a protective covering',
	'panache':'grand/flamboyand manner/verve',
	'modicum':'small amount',
	'paradigm':'pattern/framework containing basic assumptions',
	'allegory':'representation of abstract meaning through concrete material forms',
	'elegy':'a mounful poem (to honor the dead)',
	'encomium':'formal expression of high praise',
	'eulogy':'formal expression of high praise',	
	'jeremiad':'prolonged lamentation',
	'panegyric':'formal expression of high praise',
	'synergy':'cooperative action',
	'syllogism':'if A is B and B is C, then A is C; subtle clever argument',
	'amalgamation':'merge',
	'aplomb':'imperturbable poise and self-assurance; VERTICAL standing',
	'surfeit':'excess',
	'conduit':'water pipe - natural or human-made',
	'tyro':'novice',
	'guile':'insiduous cunning to achieve some goal; artful deception',
	'conjecture':'guess or theory formed without sufficient evidence',
	'poseur':'poser in French',
	'cogitation':'contemplation',
	'epicure':'connoisseur with refined taste',
	'perfidy':'breach of trust (TREACHERY)',
	'pulchritude':'physical beauty',
	'curmudgeon':'bad-tempered cranky person (think crusty old man)',
	'misanthrope':'someone who hates people/humanity'
	}
	
my_verbs = {
	'expurgate':'to purge of moral offensiveness; to censor',
	'evince':'to make evident',
	'parry':'to ward off or to dodge',
	'decry':'to denounce or condemn',
	'accede':'to agree (to); to assume office or something like that',
	'retuperate':'to address/speak of abusively',
	'revile':'to address/speak of abusively',
	'obfuscate':'to confuse; to make unclear',
	'peruse':'to skim through; to read',
	'discomfit':'to confuse/deject; to thwart plans of',
	'comport':'to behave',
	'demur':'to make an objection or an exception',
	'brandish':'to wave (like a weapon); to flourish',
	'gainsay':'to deny; to oppose',
	'scat':'to go off hastily',
	'bedizen':'to dress gaudily',
	'masticate':'to chew',
	'inveigle (into/from, resp.)':'to entice by flattery; to win beguilingly (resp.)',
	'abase':'to degrade; to lower',
	'ablate':'to eradicate',
	'extirpate':'to eradicate',
	'expatiate':'to digress',
	'delicquesce':'to become liquid; to melt away',
	'jilt':'to reject; to cast aside abruptly and unfeelingly',
	'calumniate':'to slander'
	}

my_adjectives = {
	'invidious':'hateful; injurious',
	'visceral':'relating to inner feelings rather than intellect',
	'incontrovertible':'indisputable',
	'inchoate':'rudimentary, not yet completed; INCIPIENT',
	'refractory':'unmanageable',
	'lachrymose':'mournful, tearful',
	'recondite':'little-known; obscure; dealing with profound abstruse matter',
	'gossamer':'fine filmy cobweb you see in fall; very delicate gauze oft used for veils',
	'refulgent':'shining; radiant',
	'axiomatic':'obvious/aphoristic',
	'quixotic':'extravagantly chivalrous; visionary, impractical; impulsive',
	'tendentious':'showing a definite tendency, bias, or purpose',
	'mellifluous':'sweet; smoothly flowing; flowing with honey',
	'execrable':'extremely bad',
	'transilient':'passing from one thing to another',
	'apposite':'relevant',
	'obstreperous':'unruly, noisy, boisterous',
	'rapacious':'very greedy; predatory, predacious',
	'quiescent':'at rest, quiet, still',
	'timorous':'scared, timid, characterized by/indicating fear',
	'exacting':'rigid in demands/requirements',
	'miserly':'stingy/niggardly',
	'tenuous':'thin, weak, unsubstantiated',
	'diffident':'lacking self-confidence; shy; restrained',
	'disquieting':'disturbing',
	'prolix':'tediously long and wordy',
	'penitential':'showing repentance/PENITENCE',
	'intractable':'unmanageable',
	'prodigal':'lavish and wasteful, like a lawn',
	'hackneyed':'made commonplace, banal, trite',
	'skittish':'excitable, easily scared, playful, nervous',
	'vociferous':'loud and clamorous',
	'fetid':'stinky',
	'spurious':'fake',
	'extemporaneous':'impromptu/not rehearsed',
	'germane':'relevant',
	'gregarious':'sociable',
	'seemly':'appropriate, in good taste',
	'recalcitrant':'unmanageable and resistant to control',
	'voluble':'rambling; talkative',
	'effusive':'unduly demonstrative; lacking reserve; overflowing',
	'specious':'superficially pleasing, good/plausible',
	'garrulous':'rambling; talkative',
	'pugnacious':'quarrelsome',
	'salutary':'healthful; wholesome',
	'salubrious':'healthful; wholesome',
	'facetious':'humorous; not serious',
	'commensurate':'proportionate',
	'tractable':'docile',
	'evicerate':'to remove innards from (to disembowel)',
	'petulant':'irritable; showing sudden irritation, esp. over trifling annoyance',
	'benight':'to be overtaken by darkness, especially moral darkness',
	'attenuate':'to weaken',
	'innervate':'to stimulate through nerves',
	'diurnal':'daily; belonging in the daytime',
	'didactic':'instructive',
	'sartorial':'relating to tailors',
	'trite':'stale; overused',
	'synoptic':'summary with only the main ideas',
	'lurid':'gruesome, horrible, revolting',
	'circumspect':'watchful, cautious',
	'resolute':'firmly resolved; set in opinion',
	'obsequious':'deferring like a servant; fawning',
	'profligate':'shamelessly immoral',
	'perfunctory':'performed only as a duty, hasty, superficial',
	'inimical':'bad',
	'splenetic':'irritable, peevish, spiteful',
	'diaphanous':'very sheer, light; almost transparent; delicate',
	'iniquitous':'wicked and unjust; sinful',
	'fatuous':'foolish, silly',
	'venal':'willing to be corrupt; mercenary',
	'captious':'difficult to please; finding tiny things wrong; referring to trick question',
	'nascent':'beginning to exist/develop',
	'pithy':'brief but very meaningful and forcible (often referring to expression)',
	'precarious':'dependent on circumstances beyond control',
	'blithe':'carefree',
	'inveterate':'chronic; firmly established',
	'apocryphal':'fake',
	'veracious':'truthful',
	'maladaptive':'inadequate',
	'meretritious':'fake, but in a gaudy flashy way (think: streetwalker)',
	'prodigious':'impressively huge; monstrous',
	'pusillanimous':'cowardly',
	'arrant':'downright; thorough; unmitigated; notorious',
	'desultory':'inconsistent; random',
	'endemic':'natural to or characteristic of a specific people or place; native; indigenous',
	'salient':'prominent/obvious; pointing upward',
	'ineluctable':'inescapable',
	'seminal':'relating to seed',
	'parochial':'narrow, provincial; supported by the church',
	'insouciant':'carefree',
	'piquant':'agreeably stimulating; pleasantly biting; interesting; lively',
	'parsimonious':'stingy/niggardly',
	'penurious':'stingy/niggardly',
	'perfidious':'deceitful',
	'rancorous':'bitter and malicious',
	'perspicuous':'explicit',
	'circuitous':'roundabout; not direct',
	'superannuated':'very old',
	'dulcet':'pleasant, melodious, soothing',
	'comely':'appropriate, in good taste',
	'insipient':'foolish, silly',
	'flagging':'weak and diminishing',
	'hegemonic':'full (referring to control), dominance',
	'profuse':'extravagant, given away freely; abundant',
	'magnanimous':'very noble, generous, forgiving',
	'potpurri':'pleasantly fragrant packet of dried plants',
	'tenebrous':'dark, obscure, gloomy',
	'persnickety':'fussy, difficult to take care of',
	'punctilious':'extremely strict in obserance of formalities',
	'adroit':'nimble, ingenious, resourceful',
	'limpid':'clear; lucid; calm',
	'raffish':'mildly disreputable and non-conformist; tawdy',
	'exigent':'requiring immediate attention',
	'peremptory':'(a f***ing a**hole) demanding immediate attention/obedience',
	'callow':'inexperienced; immature',
	'corpulent':'fat',
	'stygian':'dark, obscure, gloomy',
	'ebullient':'cheerful; energetic',
	'propitious':'favorable'
	}

import json
s = json.dumps(my_nouns)
with open("~//my_nouns.txt","w") as f:
	f.write(s)

s = json.dumps(my_verbs)
with open("~//my_verbs.txt","w") as f:
	f.write(s)
	
s = json.dumps(my_adjectives)
with open("~//my_adjectives.txt","w") as f:
	f.write(s)
