my_nouns = {
	'umbrage':'displeasure; the vaguest feeling of suspicion',
	'exegesis':'critical explanation/interpretation of a text, especially the Bible',
	'jaundice':'being in the state of resentment, prejudice, envy; skin discoloration',
	'maxim':'general truth or principle',
	'cupidity':'eager or excessive DESIRE',
	'approbation':'approval',
	'diatribe':'sharp bitter criticism',
	'wile':'trick; deceitful cunning',
	'predilection':'partiality',
	'affectation':'conspicuous artificiality; pretend quality',
	'callousness':'hardness; lack of sensitivity',
	'anodyne':'painkiller (medicine)',
	'dross':'waste',
	'polemic':'a controversial argument; a contrarian/contraversialist',
	'chicanery':'trickery by sophistry',
	'perspicacity':'keenness; understanding; penetration',
	'panoply':'a wide-ranging array; a protective covering',
	'panache':'grand/flamboyand manner/verve',
	'modicum':'small amount',
	'paradigm':'pattern/framework containing basic assumptions',
	'allegory':'representation of abstract meaning through concrete material forms',
	'elegy':'a mounful poem (to honor the dead)',
	'eulogy':'formal expression of high praise',	
	'jeremiad':'prolonged lamentation',
	'panegyric':'formal expression of high praise',
	'synergy':'cooperative action',
	'syllogism':'if A is B and B is C, then A is C; subtle clever argument',
	'aplomb':'imperturbable poise and self-assurance; VERTICAL standing',
	'surfeit':'excess',
	'conjecture':'guess or theory formed without sufficient evidence',
	'perfidy':'breach of trust (TREACHERY)',
	'pulchritude':'physical beauty',
	'gossamer':'fine cobweb you see in fall; very delicate gauze oft used for veils',
	'manacle':'shackles; handcuffs'
	}
	
my_verbs = {
	'retuperate':'to address/speak of abusively',
	'revile':'to address/speak of abusively',
	'discomfit':'to confuse/deject; to thwart plans of',
	'demur':'to make an objection or an exception',
	'gainsay':'to deny; to oppose',
	'inveigle (into/from, resp.)':'to entice by flattery; to win beguilingly (resp.)',
	'extirpate':'to eradicate',
	'expatiate':'to digress',
	'delicquesce':'to become liquid; to melt away',
	'jilt':'to reject; to cast aside abruptly and unfeelingly',
	'calumniate':'to slander',
	'indemnify':'to compensate; to secure against legal reponsibility',
	'bridle':'to show ones anger, especially by throwing up the head; to _ a horse',
	}

my_adjectives = {
	'invidious':'hateful; injurious',
	'plodding':'slow-moving an unexciting',
	'crestfallen':'sad and disappointed',
	'humdrum':'dull and monotonous',
	'visceral':'relating to inner feelings rather than intellect',
	'incontrovertible':'indisputable',
	'inchoate':'rudimentary, not yet completed; INCIPIENT',
	'refractory':'unmanageable',
	'lachrymose':'mournful, tearful',
	'recondite':'little-known; obscure; dealing with profound abstruse matter',
	'refulgent':'shining; radiant',
	'tenuous':'thin, weak, unsubstantiated',
	'hackneyed':'made commonplace, banal, trite',
	'gregarious':'sociable',
	'recalcitrant':'unmanageable and resistant to control',
	'voluble':'rambling; talkative',
	'effusive':'unduly demonstrative; lacking reserve; overflowing',
	'specious':'superficially pleasing, good/plausible',
	'garrulous':'rambling; talkative',
	'pugnacious':'quarrelsome',
	'salubrious':'healthful; wholesome',
	'facetious':'humorous; not serious',
	'commensurate':'proportionate',
	'tractable':'docile',
	'evicerate':'to remove innards from (to disembowel)',
	'petulant':'irritable; showing sudden irritation, esp. over trifling annoyance',
	'benight':'to be overtaken by darkness, especially moral darkness',
	'attenuate':'to weaken',
	'innervate':'to stimulate through nerves',
	'diurnal':'daily; belonging in the daytime',
	'trite':'stale; overused',
	'lurid':'gruesome, horrible, revolting',
	'circumspect':'watchful, cautious',
	'obsequious':'deferring like a servant; fawning',
	'profligate':'shamelessly immoral',
	'perfunctory':'performed only as a duty, hasty, superficial',
	'inimical':'bad',
	'splenetic':'irritable, peevish, spiteful',
	'diaphanous':'very sheer, light; almost transparent; delicate',
	'iniquitous':'wicked and unjust; sinful',
	'venal':'willing to be corrupt; mercenary',
	'captious':'difficult to please; finding tiny things wrong; referring to trick question',
	'nascent':'beginning to exist/develop',
	'blithe':'carefree',
	'inveterate':'chronic; firmly established',
	'apocryphal':'fake',
	'maladaptive':'inadequate',
	'prodigious':'impressively huge; monstrous',
	'pusillanimous':'cowardly',
	'arrant':'downright; thorough; unmitigated; notorious',
	'desultory':'inconsistent; random',
	'endemic':'natural to or characteristic of a specific people or place; native; indigenous',
	'salient':'prominent/obvious; pointing upward',
	'ineluctable':'inescapable',
	'insouciant':'carefree',
	'perfidious':'deceitful',
	'perspicuous':'explicit',
	'circuitous':'roundabout; not direct',
	'insipient':'foolish, silly',
	'hegemonic':'full (referring to control), dominance',
	'profuse':'extravagant, given away freely; abundant',
	'magnanimous':'very noble, generous, forgiving',
	'tenebrous':'dark, obscure, gloomy',
	'limpid':'clear; lucid; calm',
	'raffish':'mildly disreputable and non-conformist; tawdy',
	'exigent':'requiring immediate attention',
	'peremptory':'(a fucking asshole) demanding immediate attention/obedience',
	'callow':'inexperienced; immature',
	}

import json
s = json.dumps(my_nouns)
with open("C://Users//rv818//PythonPrograms//my_nouns.txt","w") as f:
	f.write(s)

s = json.dumps(my_verbs)
with open("C://Users//rv818//PythonPrograms//my_verbs.txt","w") as f:
	f.write(s)
	
s = json.dumps(my_adjectives)
with open("C://Users//rv818//PythonPrograms//my_adjectives.txt","w") as f:
	f.write(s)